# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(verbose_name='date published')),
                ('grau_conhecimento', models.IntegerField(default=0)),
                ('tamanho', models.IntegerField(default=0)),
                ('grau_dificuldade', models.IntegerField(default=0)),
                ('topicos', models.IntegerField(default=0)),
                ('peso', models.IntegerField(default=0)),
                ('percentual', models.FloatField()),
                ('aproveitamento', models.FloatField()),
            ],
        ),
    ]
