# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('peso', models.IntegerField(default=0)),
                ('aproveitamento', models.IntegerField(default=0)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudos.Materia')),
            ],
        ),
    ]
